# Generated by Django 4.1 on 2022-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
