# Generated by Django 4.1 on 2022-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolistitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
