# Generated by Django 4.1 on 2022-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlistitem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
